In [12]:
import pandas as pd

df = pd.read_csv('developer_survey_2018/survey_results_public.csv')

In [13]:
df

,Respondent,Hobby,OpenSource,Country,Student,Employment,FormalEducation,UndergradMajor,CompanySize,DevType,...,Exercise,Gender,SexualOrientation,EducationParents,RaceEthnicity,Age,Dependents,MilitaryUS,SurveyTooLong,SurveyEasy
0,1,Yes,No,Kenya,No,Employed part-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,20 to 99 employees,Full-stack developer,...,3 - 4 times per week,Male,Straight or heterosexual,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Black or of African descent,25 - 34 years old,Yes,NaN,The survey was an appropriate length,Very easy
1,3,Yes,Yes,United Kingdom,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A natural science (ex. biology, chemistry, phy...","10,000 or more employees",Database administrator;DevOps specialist;Full-...,...,Daily or almost every day,Male,Straight or heterosexual,"Bachelor’s degree (BA, BS, B.Eng., etc.)",White or of European descent,35 - 44 years old,Yes,NaN,The survey was an appropriate length,Somewhat easy
2,4,Yes,Yes,United States,No,Employed full-time,Associate degree,"Computer science, computer engineering, or sof...",20 to 99 employees,Engineering manager;Full-stack developer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,No,No,United States,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",100 to 499 employees,Full-stack developer,...,I don't typically exercise,Male,Straight or heterosexual,Some college/university study without earning ...,White or of European descent,35 - 44 years old,No,No,The survey was an appropriate length,Somewhat easy
4,7,Yes,No,South Africa,"Yes, part-time",Employed full-time,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","10,000 or more employees",Data or business analyst;Desktop or enterprise...,...,3 - 4 times per week,Male,Straight or heterosexual,Some college/university study without earning ...,White or of European descent,18 - 24 years old,Yes,NaN,The survey was an appropriate length,Somewhat easy
5,8,Yes,No,United Kingdom,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",10 to 19 employees,Back-end developer;Database administrator;Fron...,...,1 - 2 times per week,Male,Straight or heterosexual,"Secondary school (e.g. American high school, G...",White or of European descent,18 - 24 years old,No,NaN,The survey was an appropriate length,Somewhat easy
6,9,Yes,Yes,United States,No,Employed full-time,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","10,000 or more employees",Back-end developer;Front-end developer;Full-st...,...,I don't typically exercise,Male,Straight or heterosexual,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",White or of European descent,18 - 24 years old,No,No,The survey was an appropriate length,Somewhat easy
7,10,Yes,Yes,Nigeria,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",10 to 19 employees,Designer;Front-end developer;QA or test developer,...,1 - 2 times per week,Female,NaN,Primary/elementary school,Black or of African descent,25 - 34 years old,No,NaN,The survey was too long,Somewhat difficult
8,11,Yes,Yes,United States,No,Employed full-time,Some college/university study without earning ...,Fine arts or performing arts (ex. graphic desi...,100 to 499 employees,"Back-end developer;C-suite executive (CEO, CTO...",...,I don't typically exercise,Male,Straight or heterosexual,Some college/university study without earning ...,White or of European descent,35 - 44 years old,Yes,No,The survey was an appropriate length,Very easy
9,16,No,Yes,India,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",500 to 999 employees,Designer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,17,Yes,No,Spain,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Information systems, information technology, o...","1,000 to 4,999 employees",Back-end developer;Database administrator;Mobi...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,18,Yes,Yes,India,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",100 to 499 employees,Back-end developer;Front-end developer;Full-st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,19,Yes,No,Croatia,NaN,Employed full-time,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",20 to 99 employees,Back-end developer;Front-end developer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,20,No,No,India,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",20 to 99 employees,Back-end developer;Full-stack developer,...,I don't typically exercise,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,21,No,No,Netherlands,"Yes, full-time",Employed full-time,"Secondary school (e.g. American high school, G...",NaN,20 to 99 employees,Back-end developer;Front-end developer;Student,...,Daily or almost every day,Male,NaN,Associate degree,White or of European descent,18 - 24 years old,No,NaN,The survey was an appropriate length,Neither easy nor difficult
15,22,Yes,No,Israel,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",Fine arts or performing arts (ex. graphic desi...,"5,000 to 9,999 employees",Full-stack developer,...,3 - 4 times per week,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,26,No,No,United States,"Yes, full-time",Employed part-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","1,000 to 4,999 employees",Student,...,3 - 4 times per week,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,27,Yes,No,Sweden,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","A business discipline (ex. accounting, finance...",10 to 19 employees,Back-end developer,...,3 - 4 times per week,Male,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)",White or of European descent,35 - 44 years old,Yes,NaN,The survey was too long,Somewhat difficult
18,29,Yes,Yes,India,"Yes, full-time",Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,"10,000 or more employees",Data or business analyst;Data scientist or mac...,...,Daily or almost every day,Female,NaN,Some college/university study without earning ...,NaN,NaN,NaN,NaN,The survey was too long,Very difficult
19,31,Yes,Yes,Chile,"Yes, full-time",Employed part-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A business discipline (ex. accounting, finance...",Fewer than 10 employees,Back-end developer;Front-end developer;Full-st...,...,1 - 2 times per week,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,33,Yes,Yes,Australia,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...","1,000 to 4,999 employees",Database administrator;Full-stack developer;Mo...,...,3 - 4 times per week,Male,Straight or heterosexual,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,35 - 44 years old,Yes,NaN,The survey was too long,Neither easy nor difficult
21,34,Yes,No,United States,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,500 to 999 employees,Back-end developer;Desktop or enterprise appli...,...,Daily or almost every day,Male,Straight or heterosexual,"Bachelor’s degree (BA, BS, B.Eng., etc.)",White or of European descent,45 - 54 years old,Yes,No,The survey was too long,Very easy
22,37,No,No,United Kingdom,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",20 to 99 employees,Back-end developer;Database administrator;Desi...,...,Daily or almost every day,Male,Straight or heterosexual,"Bachelor’s degree (BA, BS, B.Eng., etc.)",White or of European descent,25 - 34 years old,No,NaN,The survey was too long,Neither easy nor difficult
23,38,Yes,No,United States,No,Employed full-time,Some college/university study without earning ...,NaN,10 to 19 employees,Back-end developer;Database administrator;DevO...,...,I don't typically exercise,"Female;Male;Transgender;Non-binary, genderquee...",NaN,They never completed any formal education,White or of European descent,45 - 54 years old,Yes,No,The survey was too long,Very easy
24,39,Yes,No,India,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",100 to 499 employees,Mobile developer,...,Daily or almost every day,Female;Male,NaN,NaN,NaN,25 - 34 years old,No,NaN,The survey was too long,Very easy
25,41,Yes,Yes,Greece,"Yes, full-time",Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","A natural science (ex. biology, chemistry, phy...",20 to 99 employees,Full-stack developer,...,3 - 4 times per week,Male,Straight or heterosexual,"Bachelor’s degree (BA, BS, B.Eng., etc.)",White or of European descent,35 - 44 years old,Yes,NaN,The survey was too long,Very easy
26,43,Yes,Yes,Sweden,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...","1,000 to 4,999 employees",Front-end developer;Full-stack developer,...,1 - 2 times per week,Male,Straight or heterosexual,"Secondary school (e.g. American high school, G...",Hispanic or Latino/Latina;White or of European...,25 - 34 years old,Yes,NaN,The survey was an appropriate length,Somewhat easy
27,44,No,No,United States,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A social science (ex. anthropology, psychology...",100 to 499 employees,Back-end developer;Full-stack developer,...,I don't typically exercise,Male,Straight or heterosexual,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",White or of European descent,25 - 34 years old,No,No,The survey was too long,Very easy
28,45,Yes,Yes,United States,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","10,000 or more employees",Back-end developer;Data scientist or machine l...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,46,Yes,Yes,United Kingdom,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Fewer than 10 employees,Back-end developer;Front-end developer;Full-st...,...,I don't typically exercise,NaN,NaN,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",Black or of African descent;East Asian;Hispani...,35 - 44 years old,Yes,NaN,The survey was too long,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98825,101084,Yes,No,India,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98826,101085,Yes,Yes,Russian Federation,No,Employed full-time,Some college/university study without earning ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98827,101114,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98828,101120,No,No,Russian Federation,NaN,Employed full-time,Primary/elementary school,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98829,101138,Yes,Yes,Netherlands,"Yes, full-time",Employed part-time,"Secondary school (e.g. American high school, G...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98830,101151,Yes,Yes,India,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98831,101152,Yes,No,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98832,101154,Yes,Yes,Netherlands,No,Employed full-time,Some college/university study without earning ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98833,101170,Yes,No,India,"Yes, full-time","Not employed, but looking for work","Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,Back-end developer;QA or test developer;Student,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98834,101185,Yes,Yes,Poland,NaN,"Not employed, and not looking for work",Primary/elementary school,NaN,NaN,Back-end developer;Designer;Student,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98835,101200,Yes,Yes,Viet Nam,"Yes, full-time",NaN,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98836,101202,Yes,Yes,"Iran, Islamic Republic of...","Yes, full-time",Employed full-time,I never completed any formal education,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98837,101205,Yes,No,Czech Republic,"Yes, full-time","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98838,101258,No,No,Poland,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98839,101263,Yes,Yes,India,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98840,101281,Yes,Yes,India,"Yes, part-time",Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98841,101310,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98842,101358,Yes,Yes,Pakistan,No,Employed full-time,Some college/university study without earning ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98843,101366,Yes,No,Indonesia,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98844,101371,Yes,Yes,India,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98845,101391,No,Yes,India,"Yes, full-time",Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98846,101396,Yes,Yes,Azerbaijan,NaN,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98847,101411,No,No,United States,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98848,101432,Yes,No,India,"Yes, full-time",Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98849,101478,No,Yes,India,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98850,101513,Yes,Yes,United States,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98851,101531,No,Yes,Spain,"Yes, full-time","Not employed, but looking for work",NaN,NaN,NaN,Back-end developer;Front-end developer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98852,101541,Yes,Yes,India,"Yes, full-time",Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98853,101544,Yes,No,Russian Federation,No,"Independent contractor, freelancer, or self-em...",Some college/university study without earning ...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98854,101548,Yes,Yes,Cambodia,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
df.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98855 entries, 0 to 98854
Data columns (total 129 columns):
Respondent                     98855 non-null int64
Hobby                          98855 non-null object
OpenSource                     98855 non-null object
Country                        98443 non-null object
Student                        94901 non-null object
Employment                     95321 non-null object
FormalEducation                94703 non-null object
UndergradMajor                 79036 non-null object
CompanySize                    71531 non-null object
DevType                        92098 non-null object
YearsCoding                    93835 non-null object
YearsCodingProf                77903 non-null object
JobSatisfaction                69276 non-null object
CareerSatisfaction             76504 non-null object
HopeFiveYears                  75718 non-null object
JobSearchStatus                79488 non-null object
LastNewJob                     78889 non-null object
AssessJob1                     66985 non-null float64
AssessJob2                     66985 non-null float64
AssessJob3                     66985 non-null float64
AssessJob4                     66985 non-null float64
AssessJob5                     66985 non-null float64
AssessJob6                     66985 non-null float64
AssessJob7                     66985 non-null float64
AssessJob8                     66985 non-null float64
AssessJob9                     66985 non-null float64
AssessJob10                    66985 non-null float64
AssessBenefits1                64918 non-null float64
AssessBenefits2                64918 non-null float64
AssessBenefits3                64918 non-null float64
AssessBenefits4                64918 non-null float64
AssessBenefits5                64918 non-null float64
AssessBenefits6                64918 non-null float64
AssessBenefits7                64918 non-null float64
AssessBenefits8                64918 non-null float64
AssessBenefits9                64918 non-null float64
AssessBenefits10               64918 non-null float64
AssessBenefits11               64917 non-null float64
JobContactPriorities1          48706 non-null float64
JobContactPriorities2          48706 non-null float64
JobContactPriorities3          48706 non-null float64
JobContactPriorities4          48706 non-null float64
JobContactPriorities5          48706 non-null float64
JobEmailPriorities1            46213 non-null float64
JobEmailPriorities2            46213 non-null float64
JobEmailPriorities3            46213 non-null float64
JobEmailPriorities4            46213 non-null float64
JobEmailPriorities5            46213 non-null float64
JobEmailPriorities6            46213 non-null float64
JobEmailPriorities7            46213 non-null float64
UpdateCV                       65539 non-null object
Currency                       62008 non-null object
Salary                         50578 non-null object
SalaryType                     51070 non-null object
ConvertedSalary                47702 non-null float64
CurrencySymbol                 58650 non-null object
CommunicationTools             56970 non-null object
TimeFullyProductive            51872 non-null object
EducationTypes                 67960 non-null object
SelfTaughtTypes                57354 non-null object
TimeAfterBootcamp              6652 non-null object
HackathonReasons               25691 non-null object
AgreeDisagree1                 68217 non-null object
AgreeDisagree2                 68346 non-null object
AgreeDisagree3                 68364 non-null object
LanguageWorkedWith             78334 non-null object
LanguageDesireNextYear         73244 non-null object
DatabaseWorkedWith             66270 non-null object
DatabaseDesireNextYear         57498 non-null object
PlatformWorkedWith             65999 non-null object
PlatformDesireNextYear         61353 non-null object
FrameworkWorkedWith            51620 non-null object
FrameworkDesireNextYear        55218 non-null object
IDE                            75398 non-null object
OperatingSystem                76179 non-null object
NumberMonitors                 76398 non-null object
Methodology                    58981 non-null object
VersionControl                 74298 non-null object
CheckInCode                    72355 non-null object
AdBlocker                      76055 non-null object
AdBlockerDisable               54898 non-null object
AdBlockerReasons               37745 non-null object
AdsAgreeDisagree1              74485 non-null object
AdsAgreeDisagree2              74413 non-null object
AdsAgreeDisagree3              74414 non-null object
AdsActions                     59514 non-null object
AdsPriorities1                 60479 non-null float64
AdsPriorities2                 60479 non-null float64
AdsPriorities3                 60479 non-null float64
AdsPriorities4                 60479 non-null float64
AdsPriorities5                 60479 non-null float64
AdsPriorities6                 60479 non-null float64
AdsPriorities7                 60479 non-null float64
AIDangerous                    63115 non-null object
AIInteresting                  65367 non-null object
AIResponsible                  65553 non-null object
AIFuture                       69728 non-null object
EthicsChoice                   70782 non-null object
EthicsReport                   70426 non-null object
EthicsResponsible              64540 non-null object
EthicalImplications            69309 non-null object
StackOverflowRecommend         76489 non-null object
StackOverflowVisit             76811 non-null object
StackOverflowHasAccount        76791 non-null object
StackOverflowParticipate       65740 non-null object
StackOverflowJobs              75297 non-null object
StackOverflowDevStory          65677 non-null object
StackOverflowJobsRecommend     38317 non-null object
StackOverflowConsiderMember    76007 non-null object
HypotheticalTools1             70068 non-null object
HypotheticalTools2             70052 non-null object
HypotheticalTools3             69999 non-null object
HypotheticalTools4             69986 non-null object
HypotheticalTools5             70045 non-null object
WakeTime                       72146 non-null object
HoursComputer                  72133 non-null object
HoursOutside                   72024 non-null object
SkipMeals                      71946 non-null object
ErgonomicDevices               34058 non-null object
Exercise                       72108 non-null object
Gender                         64469 non-null object
SexualOrientation              59765 non-null object
EducationParents               61813 non-null object
RaceEthnicity                  57473 non-null object
Age                            64574 non-null object
Dependents                     62596 non-null object
MilitaryUS                     15781 non-null object
SurveyTooLong                  65941 non-null object
SurveyEasy                     65879 non-null object
dtypes: float64(41), int64(1), object(87)
memory usage: 97.3+ MB

In [15]:
columns_keep = ['Country', 'Student', 'Employment', 'FormalEducation', 'UndergradMajor', 'CompanySize',
               'DevType','YearsCoding','JobSatisfaction','JobSearchStatus','LastNewJob',
               'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith','PlatformWorkedWith',
               'PlatformDesireNextYear','IDE','OperatingSystem',
               'HoursComputer','HoursOutside','SkipMeals','Exercise','Gender','EducationParents','Age','Dependents']

len(columns_keep)

26

In [16]:
df = df[columns_keep]

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98855 entries, 0 to 98854
Data columns (total 26 columns):
Country                   98443 non-null object
Student                   94901 non-null object
Employment                95321 non-null object
FormalEducation           94703 non-null object
UndergradMajor            79036 non-null object
CompanySize               71531 non-null object
DevType                   92098 non-null object
YearsCoding               93835 non-null object
JobSatisfaction           69276 non-null object
JobSearchStatus           79488 non-null object
LastNewJob                78889 non-null object
LanguageWorkedWith        78334 non-null object
LanguageDesireNextYear    73244 non-null object
DatabaseWorkedWith        66270 non-null object
PlatformWorkedWith        65999 non-null object
PlatformDesireNextYear    61353 non-null object
IDE                       75398 non-null object
OperatingSystem           76179 non-null object
HoursComputer             72133 non-null object
HoursOutside              72024 non-null object
SkipMeals                 71946 non-null object
Exercise                  72108 non-null object
Gender                    64469 non-null object
EducationParents          61813 non-null object
Age                       64574 non-null object
Dependents                62596 non-null object
dtypes: object(26)
memory usage: 19.6+ MB

In [18]:
#df.to_csv('selected_columns.csv')

In [19]:
df

,Country,Student,Employment,FormalEducation,UndergradMajor,CompanySize,DevType,YearsCoding,JobSatisfaction,JobSearchStatus,...,IDE,OperatingSystem,HoursComputer,HoursOutside,SkipMeals,Exercise,Gender,EducationParents,Age,Dependents
0,Kenya,No,Employed part-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,20 to 99 employees,Full-stack developer,3-5 years,Extremely satisfied,"I’m not actively looking, but I am open to new...",...,Komodo;Vim;Visual Studio Code,Linux-based,9 - 12 hours,1 - 2 hours,Never,3 - 4 times per week,Male,"Bachelor’s degree (BA, BS, B.Eng., etc.)",25 - 34 years old,Yes
1,United Kingdom,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A natural science (ex. biology, chemistry, phy...","10,000 or more employees",Database administrator;DevOps specialist;Full-...,30 or more years,Moderately dissatisfied,I am actively looking for a job,...,IPython / Jupyter;Sublime Text;Vim,Linux-based,5 - 8 hours,30 - 59 minutes,Never,Daily or almost every day,Male,"Bachelor’s degree (BA, BS, B.Eng., etc.)",35 - 44 years old,Yes
2,United States,No,Employed full-time,Associate degree,"Computer science, computer engineering, or sof...",20 to 99 employees,Engineering manager;Full-stack developer,24-26 years,Moderately satisfied,"I’m not actively looking, but I am open to new...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,United States,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",100 to 499 employees,Full-stack developer,18-20 years,Neither satisfied nor dissatisfied,"I’m not actively looking, but I am open to new...",...,Visual Studio;Visual Studio Code,Windows,9 - 12 hours,Less than 30 minutes,3 - 4 times per week,I don't typically exercise,Male,Some college/university study without earning ...,35 - 44 years old,No
4,South Africa,"Yes, part-time",Employed full-time,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","10,000 or more employees",Data or business analyst;Desktop or enterprise...,6-8 years,Slightly satisfied,"I’m not actively looking, but I am open to new...",...,Notepad++;Visual Studio;Visual Studio Code,Windows,Over 12 hours,1 - 2 hours,Never,3 - 4 times per week,Male,Some college/university study without earning ...,18 - 24 years old,Yes
5,United Kingdom,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",10 to 19 employees,Back-end developer;Database administrator;Fron...,6-8 years,Moderately satisfied,I am actively looking for a job,...,IntelliJ;PyCharm;Visual Studio Code,Linux-based,9 - 12 hours,30 - 59 minutes,1 - 2 times per week,1 - 2 times per week,Male,"Secondary school (e.g. American high school, G...",18 - 24 years old,No
6,United States,No,Employed full-time,Some college/university study without earning ...,"Computer science, computer engineering, or sof...","10,000 or more employees",Back-end developer;Front-end developer;Full-st...,9-11 years,Slightly satisfied,"I’m not actively looking, but I am open to new...",...,Atom;Visual Studio Code,MacOS,Over 12 hours,Less than 30 minutes,1 - 2 times per week,I don't typically exercise,Male,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",18 - 24 years old,No
7,Nigeria,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",10 to 19 employees,Designer;Front-end developer;QA or test developer,0-2 years,Slightly satisfied,"I’m not actively looking, but I am open to new...",...,Atom;Notepad++;Sublime Text;Visual Studio Code,Windows,Over 12 hours,1 - 2 hours,Daily or almost every day,1 - 2 times per week,Female,Primary/elementary school,25 - 34 years old,No
8,United States,No,Employed full-time,Some college/university study without earning ...,Fine arts or performing arts (ex. graphic desi...,100 to 499 employees,"Back-end developer;C-suite executive (CEO, CTO...",30 or more years,Moderately satisfied,"I’m not actively looking, but I am open to new...",...,IntelliJ;PyCharm;Sublime Text;Vim,MacOS,9 - 12 hours,Less than 30 minutes,1 - 2 times per week,I don't typically exercise,Male,Some college/university study without earning ...,35 - 44 years old,Yes
9,India,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",500 to 999 employees,Designer,0-2 years,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Spain,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Information systems, information technology, o...","1,000 to 4,999 employees",Back-end developer;Database administrator;Mobi...,6-8 years,Moderately dissatisfied,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,India,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",100 to 499 employees,Back-end developer;Front-end developer;Full-st...,0-2 years,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Croatia,NaN,Employed full-time,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",20 to 99 employees,Back-end developer;Front-end developer,0-2 years,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,India,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",20 to 99 employees,Back-end developer;Full-stack developer,3-5 years,Extremely satisfied,"I’m not actively looking, but I am open to new...",...,Eclipse;NetBeans,Linux-based,5 - 8 hours,1 - 2 hours,Never,I don't typically exercise,NaN,NaN,NaN,NaN
14,Netherlands,"Yes, full-time",Employed full-time,"Secondary school (e.g. American high school, G...",NaN,20 to 99 employees,Back-end developer;Front-end developer;Student,0-2 years,Neither satisfied nor dissatisfied,"I’m not actively looking, but I am open to new...",...,Notepad++;Visual Studio,Windows,9 - 12 hours,1 - 2 hours,Never,Daily or almost every day,Male,Associate degree,18 - 24 years old,No
15,Israel,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",Fine arts or performing arts (ex. graphic desi...,"5,000 to 9,999 employees",Full-stack developer,3-5 years,Moderately dissatisfied,"I’m not actively looking, but I am open to new...",...,NaN,NaN,9 - 12 hours,1 - 2 hours,Never,3 - 4 times per week,NaN,NaN,NaN,NaN
16,United States,"Yes, full-time",Employed part-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","1,000 to 4,999 employees",Student,0-2 years,NaN,I am actively looking for a job,...,NaN,NaN,5 - 8 hours,30 - 59 minutes,Never,3 - 4 times per week,NaN,NaN,NaN,NaN
17,Sweden,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","A business discipline (ex. accounting, finance...",10 to 19 employees,Back-end developer,6-8 years,Moderately satisfied,"I’m not actively looking, but I am open to new...",...,Visual Studio;Visual Studio Code,Windows,9 - 12 hours,30 - 59 minutes,Never,3 - 4 times per week,Male,"Bachelor’s degree (BA, BS, B.Eng., etc.)",35 - 44 years old,Yes
18,India,"Yes, full-time",Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,"10,000 or more employees",Data or business analyst;Data scientist or mac...,0-2 years,Slightly satisfied,"I’m not actively looking, but I am open to new...",...,Android Studio;Coda;Xcode,Windows,9 - 12 hours,1 - 2 hours,3 - 4 times per week,Daily or almost every day,Female,Some college/university study without earning ...,NaN,NaN
19,Chile,"Yes, full-time",Employed part-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A business discipline (ex. accounting, finance...",Fewer than 10 employees,Back-end developer;Front-end developer;Full-st...,3-5 years,NaN,NaN,...,NaN,NaN,9 - 12 hours,30 - 59 minutes,1 - 2 times per week,1 - 2 times per week,NaN,NaN,NaN,NaN
20,Australia,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...","1,000 to 4,999 employees",Database administrator;Full-stack developer;Mo...,15-17 years,Slightly satisfied,"I’m not actively looking, but I am open to new...",...,Android Studio;Sublime Text;Visual Studio Code...,MacOS,9 - 12 hours,30 - 59 minutes,Never,3 - 4 times per week,Male,"Bachelor’s degree (BA, BS, B.Eng., etc.)",35 - 44 years old,Yes
21,United States,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,500 to 999 employees,Back-end developer;Desktop or enterprise appli...,24-26 years,Extremely satisfied,"I’m not actively looking, but I am open to new...",...,Visual Studio;Visual Studio Code,MacOS,5 - 8 hours,1 - 2 hours,NaN,Daily or almost every day,Male,"Bachelor’s degree (BA, BS, B.Eng., etc.)",45 - 54 years old,Yes
22,United Kingdom,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",20 to 99 employees,Back-end developer;Database administrator;Desi...,9-11 years,Slightly satisfied,I am not interested in new job opportunities,...,Notepad++;Visual Studio;Visual Studio Code,Windows,5 - 8 hours,30 - 59 minutes,Never,Daily or almost every day,Male,"Bachelor’s degree (BA, BS, B.Eng., etc.)",25 - 34 years old,No
23,United States,No,Employed full-time,Some college/university study without earning ...,NaN,10 to 19 employees,Back-end developer;Database administrator;DevO...,18-20 years,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",...,Atom;Notepad++;PHPStorm,MacOS,5 - 8 hours,Less than 30 minutes,Daily or almost every day,I don't typically exercise,"Female;Male;Transgender;Non-binary, genderquee...",They never completed any formal education,45 - 54 years old,Yes
24,India,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",100 to 499 employees,Mobile developer,3-5 years,Moderately satisfied,"I’m not actively looking, but I am open to new...",...,Android Studio;Eclipse;IntelliJ;Notepad++;Subl...,MacOS,9 - 12 hours,1 - 2 hours,1 - 2 times per week,Daily or almost every day,Female;Male,NaN,25 - 34 years old,No
25,Greece,"Yes, full-time",Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","A natural science (ex. biology, chemistry, phy...",20 to 99 employees,Full-stack developer,9-11 years,Slightly dissatisfied,"I’m not actively looking, but I am open to new...",...,Android Studio;NetBeans;Visual Studio,Linux-based,9 - 12 hours,1 - 2 hours,Never,3 - 4 times per week,Male,"Bachelor’s degree (BA, BS, B.Eng., etc.)",35 - 44 years old,Yes
26,Sweden,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...","1,000 to 4,999 employees",Front-end developer;Full-stack developer,12-14 years,Moderately satisfied,"I’m not actively looking, but I am open to new...",...,Visual Studio Code,MacOS,5 - 8 hours,1 - 2 hours,1 - 2 times per week,1 - 2 times per week,Male,"Secondary school (e.g. American high school, G...",25 - 34 years old,Yes
27,United States,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","A social science (ex. anthropology, psychology...",100 to 499 employees,Back-end developer;Full-stack developer,3-5 years,Moderately satisfied,I am not interested in new job opportunities,...,Notepad++;Visual Studio;Visual Studio Code,Windows,5 - 8 hours,30 - 59 minutes,1 - 2 times per week,I don't typically exercise,Male,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",25 - 34 years old,No
28,United States,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","10,000 or more employees",Back-end developer;Data scientist or machine l...,6-8 years,Extremely satisfied,I am not interested in new job opportunities,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,United Kingdom,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Fewer than 10 employees,Back-end developer;Front-end developer;Full-st...,9-11 years,Neither satisfied nor dissatisfied,"I’m not actively looking, but I am open to new...",...,NaN,MacOS,9 - 12 hours,30 - 59 minutes,1 - 2 times per week,I don't typically exercise,NaN,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",35 - 44 years old,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98825,India,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98826,Russian Federation,No,Employed full-time,Some college/university study without earning ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98827,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98828,Russian Federation,NaN,Employed full-time,Primary/elementary school,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98829,Netherlands,"Yes, full-time",Employed part-time,"Secondary school (e.g. American high school, G...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98830,India,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98831,Russian Federation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98832,Netherlands,No,Employed full-time,Some college/university study without earning ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98833,India,"Yes, full-time","Not employed, but looking for work","Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,Back-end developer;QA or test developer;Student,0-2 years,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98834,Poland,NaN,"Not employed, and not looking for work",Primary/elementary school,NaN,NaN,Back-end developer;Designer;Student,3-5 years,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98835,Viet Nam,"Yes, full-time",NaN,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98836,"Iran, Islamic Republic of...","Yes, full-time",Employed full-time,I never completed any formal education,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98837,Czech Republic,"Yes, full-time","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98838,Poland,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98839,India,No,Employed full-time,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98840,India,"Yes, part-time",Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98842,Pakistan,No,Employed full-time,Some college/university study without earning ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98843,Indonesia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98844,India,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98845,India,"Yes, full-time",Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98846,Azerbaijan,NaN,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98847,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98848,India,"Yes, full-time",Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98849,India,No,Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98850,United States,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98851,Spain,"Yes, full-time","Not employed, but looking for work",NaN,NaN,NaN,Back-end developer;Front-end developer,0-2 years,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98852,India,"Yes, full-time",Employed full-time,"Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98853,Russian Federation,No,"Independent contractor, freelancer, or self-em...",Some college/university study without earning ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98854,Cambodia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df = pd.read_csv('selected_columns.csv', index_col = 0)

def regroup_country(x):
    if x != 'United States' and x != 'India' and pd.isnull(x) == False:
        x = 'Others_Country'
    return x
    
def regroup_education(x):
    if x != 'Bachelor’s degree (BA, BS, B.Eng., etc.)' and x != 'Master’s degree (MA, MS, M.Eng., MBA, etc.)' and x!= 'Other doctoral degree (Ph.D, Ed.D., etc.)' and pd.isnull(x) == False:
        x = 'Below Bachelor'
    try:
        x = x.replace('Bachelor’s degree (BA, BS, B.Eng., etc.)',"Bachelor")
        x = x.replace('Master’s degree (MA, MS, M.Eng., MBA, etc.)',"Master")
        x = x.replace('Other doctoral degree (Ph.D, Ed.D., etc.)',"PhD.")
    except:
        pass

    return x
    
def regroup_years_coding(x):
    try:
        x = x.replace('12-14 years',"12-17 years")
        x = x.replace('15-17 years',"12-17 years")
        x = x.replace('18-20 years',"18+ years")
        x = x.replace('21-23 years',"18+ years")
        x = x.replace('24-26 years',"18+ years")
        x = x.replace('27-29 years',"18+ years")
        x = x.replace('30 or more years',"18+ years")
    except:
        pass

    return x
    
def job_satisfaction_level(x):
    try:
        x = x.replace('Extremely dissatisfied','0')
        x = x.replace('Moderately dissatisfied','1')
        x = x.replace('Slightly dissatisfied','2')
        x = x.replace('Neither satisfied nor dissatisfied','3')
        x = x.replace('Slightly satisfied','4')
        x = x.replace('Moderately satisfied','5')
        x = x.replace('Extremely satisfied','6')
        x = int(x)
    except:
        pass

    return x

def regroup_gender(x):
    if x != 'Male' and x != 'Female' and pd.isnull(x) == False:
        x = 'Other_Genders'
    return x

def regroup_age(x):
    try:
        x = x.replace('45 - 54 years old',"45 years or older")
        x = x.replace('55 - 64 years old',"45 years or older")
        x = x.replace('65 years or older',"45 years or older")
    except:
        pass

    return x


df['Country'] = df['Country'].apply(regroup_country)
df['FormalEducation'] = df['FormalEducation'].apply(regroup_education)
df['YearsCoding'] = df['YearsCoding'].apply(regroup_years_coding)
df['JobSatisfaction'] = df['JobSatisfaction'].apply(job_satisfaction_level)
df['Gender'] = df['Gender'].apply(regroup_gender)
df['EducationParents'] = df['EducationParents'].apply(regroup_education)
df['Age'] = df['Age'].apply(regroup_age)

categorical_col = ['Country', 'Student', 'Employment', 'FormalEducation', 'UndergradMajor',
       'CompanySize', 'YearsCoding', 'LastNewJob', 'OperatingSystem', 'HoursComputer',
       'HoursOutside', 'SkipMeals', 'Exercise', 'Gender', 'EducationParents',
       'Age', 'Dependents']



for col in categorical_col:
    dummy_df = pd.get_dummies(df[col])
    df = df.join(dummy_df, on= df.index , how='left', rsuffix= '_'+col)
    
df = df.drop(categorical_col,axis=1)

In [52]:
df.to_csv('dummied_basic_features.csv')

In [53]:
df.columns

Index(['DevType', 'JobSatisfaction', 'JobSearchStatus', 'LanguageWorkedWith',
       'LanguageDesireNextYear', 'DatabaseWorkedWith', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'IDE', 'India', 'Others_Country',
       'United States', 'No', 'Yes, full-time', 'Yes, part-time',
       'Employed full-time', 'Employed part-time',
       'Independent contractor, freelancer, or self-employed',
       'Not employed, and not looking for work',
       'Not employed, but looking for work', 'Retired', 'Bachelor',
       'Below Bachelor', 'Master', 'PhD.',
       'A business discipline (ex. accounting, finance, marketing)',
       'A health science (ex. nursing, pharmacy, radiology)',
       'A humanities discipline (ex. literature, history, philosophy)',
       'A natural science (ex. biology, chemistry, physics)',
       'A social science (ex. anthropology, psychology, political science)',
       'Another engineering discipline (ex. civil, electrical, mechanical)',
       'Computer science, computer engineering, or software engineering',
       'Fine arts or performing arts (ex. graphic design, music, studio art)',
       'I never declared a major',
       'Information systems, information technology, or system administration',
       'Mathematics or statistics', 'Web development or web design',
       '1,000 to 4,999 employees', '10 to 19 employees',
       '10,000 or more employees', '100 to 499 employees',
       '20 to 99 employees', '5,000 to 9,999 employees',
       '500 to 999 employees', 'Fewer than 10 employees', '0-2 years',
       '12-17 years', '18+ years', '3-5 years', '6-8 years', '9-11 years',
       'Between 1 and 2 years ago', 'Between 2 and 4 years ago',
       'I've never had a job', 'Less than a year ago', 'More than 4 years ago',
       'BSD/Unix', 'Linux-based', 'MacOS', 'Windows', '1 - 4 hours',
       '5 - 8 hours', '9 - 12 hours', 'Less than 1 hour', 'Over 12 hours',
       '1 - 2 hours', '3 - 4 hours', '30 - 59 minutes', 'Less than 30 minutes',
       'Over 4 hours', '1 - 2 times per week', '3 - 4 times per week',
       'Daily or almost every day', 'Never', '1 - 2 times per week_Exercise',
       '3 - 4 times per week_Exercise', 'Daily or almost every day_Exercise',
       'I don't typically exercise', 'Female', 'Male', 'Other_Genders',
       'Bachelor_EducationParents', 'Below Bachelor_EducationParents',
       'Master_EducationParents', 'PhD._EducationParents', '18 - 24 years old',
       '25 - 34 years old', '35 - 44 years old', '45 years or older',
       'Under 18 years old', 'No_Dependents', 'Yes'],
      dtype='object')